在MATLAB里，`*` 代表矩阵乘法。但是在numpy里，`*`表示element-wise prodct。要想做到矩阵乘法，要用多函数dot:

In [2]:
import numpy as np

In [5]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [6]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [7]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [8]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

`x.dot(y)`等同于`np.dot(x, y)`:

In [9]:
np.dot(x, y)

array([[  28.,   64.],
       [  67.,  181.]])

一个二维数组和一个一维数组的矩阵乘法，得到一个一维数组：

In [10]:
np.dot(x, np.ones(3))  
# 这里应该是用狂了boradcasting，x中的每一行与[1, 1, 1]点对点乘积后求和

array([  6.,  15.])

`@`作为一个中缀计算符（鬼知道这是什么东西），也能实现矩阵乘法：

In [13]:
x @ np.ones(3)

array([  6.,  15.])

`np.linalg`能用来做矩阵分解，以及比如转置和求秩之类的事情：

In [14]:
from numpy.linalg import inv, qr

In [31]:
# X = np.round(np.random.randn(5, 5), 3) # 这里我们用np.round控制小数点后的位数，看起来更舒服一些
X = np.random.randn(5, 5)
X

array([[ 0.0761557 , -0.34138565, -0.56325926,  1.7854    ,  1.23440008],
       [ 1.46787829,  1.73130465,  1.03519282,  1.11137573, -0.05928319],
       [-0.95508009, -1.35350494, -1.43415583, -0.28499706,  0.32739284],
       [ 0.83307271,  1.89349058,  0.94116452,  0.32347353,  0.22236912],
       [-1.20661273,  0.4531822 ,  0.47635565, -1.69312137, -0.34497803]])

In [41]:
mat = X.T.dot(X)
np.round(mat, 2)

array([[ 5.22,  4.84,  3.06,  4.35,  0.3 ],
       [ 4.84,  8.74,  5.92,  1.55, -0.7 ],
       [ 3.06,  5.92,  4.56,  0.05, -1.18],
       [ 4.35,  1.55,  0.05,  7.48,  2.7 ],
       [ 0.3 , -0.7 , -1.18,  2.7 ,  1.8 ]])

In [40]:
np.round(inv(mat), 2)

array([[ 12.14,  -6.15,   3.85, -11.22,  14.95],
       [ -6.15,   4.85,  -4.47,   5.7 ,  -8.57],
       [  3.85,  -4.47,   5.23,  -3.78,   6.71],
       [-11.22,   5.7 ,  -3.78,  10.77, -14.55],
       [ 14.95,  -8.57,   6.71, -14.55,  20.95]])

In [35]:
np.round(mat.dot(inv(mat)), 2)

array([[ 1.,  0.,  0.,  0., -0.],
       [-0.,  1.,  0., -0., -0.],
       [ 0., -0.,  1., -0.,  0.],
       [-0.,  0.,  0.,  1.,  0.],
       [ 0.,  0., -0.,  0.,  1.]])

In [36]:
q, r = qr(mat)

In [38]:
np.round(r, 2)

array([[ -8.89, -10.37,  -6.57,  -7.16,  -0.77],
       [  0.  ,  -5.5 ,  -4.79,   5.41,   3.04],
       [  0.  ,   0.  ,  -0.71,   1.85,   1.54],
       [  0.  ,   0.  ,   0.  ,  -0.75,  -0.53],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.03]])

`X.T.dot(X)`计算的是X和X的转置的矩阵乘法。

一些常用的numpy.linalg函数：

![](http://oydgk2hgw.bkt.clouddn.com/pydata-book/3jol9.png)

![](http://oydgk2hgw.bkt.clouddn.com/pydata-book/5nfep.png)