# A.2 Advanced Array Manipulation（数组操作的高级用法）

# 1 Reshaping Arrays（数组变形）

有时候，我们需要在不复制的情况下改变数组的形状。调用数组的实例方法reshape，只需要给reshape传递一个元组就可以了。比如，假设我们有一个一维数组，我们想把它变成一个矩阵：

![](http://oydgk2hgw.bkt.clouddn.com/pydata-book/hwi0k.png)



In [1]:
import numpy as np

In [2]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

一个多维数组也能被变形：

In [4]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

另外可以把-1传入作为维度，这会让函数自己推测创建合适的数据维度：

In [6]:
arr = np.arange(15)

In [7]:
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

因为数组的shape属性是一个元组，所以这个东西也能传给reshape:

In [8]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [9]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

把一个高维数组变为一维数组的方法，通常称为压扁或散开（flattening or raveling）：

In [10]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

如果产生的结果在原来的数组中是连续的，ravel不会产生一份新的数据。flatten方法和revel的效果是一样的，不过flatten不论何时都是返回一份新数据：

In [12]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 2 C Versus Fortran Order（C顺序对Fortran顺序）

默认情况下，numpy是按以行为主（row major）的顺序连创建数组的。如果我们要建一个二维数组，数组的每一行是存在内存中相邻位置上的。另一个是列为主（column major）顺序，即每一列是存在内存中相邻位置上的。

因为历史原因，这种行为主和列为主的顺序也被称作为C顺序和Fortran顺序。

reshape和ravel这样的函数，接受一个order参数，用来指明数组中数据的顺序。通常用'C'或'F'来表示：

In [13]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
arr.ravel('C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

如果是给2维以上的数组变形，就有点麻烦了（参见前一节A.1 Figure A-3）。C顺序和Fortran顺序最关键的不同是哪个维度先走：

- C/row 顺序：先遍历高纬度（axis 1在axis 0之前）
- Fortran/column 顺序：最后遍历高纬度（axis 0在axis 1之前）

# 3 Concatenating and Splitting Arrays（连接和分割数组）

numpy.concatenate能接受一个由数组组成的序列（tupe，list等等），并把它们按指定的轴连接起来：

In [18]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

还有一些遍历的函数，比如vstack和hstack：

In [20]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

split可以沿着轴把一个数组分割为不同的数组：

In [22]:
arr = np.random.randn(5, 2)
arr

array([[-0.6626365 ,  0.89670682],
       [-0.4704913 ,  0.4210701 ],
       [-1.56760602, -0.983285  ],
       [-0.55348318,  0.9946369 ],
       [ 0.27884286, -1.01013025]])

In [23]:
first, second, third = np.split(arr, [1, 3])
first

array([[-0.6626365 ,  0.89670682]])

In [24]:
second

array([[-0.4704913 ,  0.4210701 ],
       [-1.56760602, -0.983285  ]])

In [25]:
third

array([[-0.55348318,  0.9946369 ],
       [ 0.27884286, -1.01013025]])

传入split的`[1, 3]`表示用于进行分割的数组的索引，即按照索引1和索引3对整个数组进行分割。

下表有一些用于连接和分割的常见函数：

![](http://oydgk2hgw.bkt.clouddn.com/pydata-book/835tm.png)

#### stacking helpers: `r_` and `c_`

在numpy的命名空间里有两个特别的对象，`r_` and `c_`，能让堆叠更简洁：

In [26]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)

In [27]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 1.54489462,  0.34506757],
       [-0.46610009,  1.01601243],
       [ 0.55942061,  0.28939793]])

In [28]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 1.54489462,  0.34506757,  3.        ],
       [-0.46610009,  1.01601243,  4.        ],
       [ 0.55942061,  0.28939793,  5.        ]])

这种用法还可以把切片转换为数组：

In [30]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

更详细的内容请看`r_` and `c_`的文档。

# 4 Repeating Elements: tile and repeat（重复元素：tile和repeat）

repeat和tile函数可以用来重复元素，方便产生一个很大的数组。repeat把每一个元素复制多次，产生一个更大的数组：

In [32]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [33]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

>注意：如果使用numpy的话，复制数组的需求是不大的，因为numpy的broadcasting能更好地满足这个需求，下一节会进行介绍

默认，如果传入一个整数，每一个元素会按这个数字进行重复。如果传入的是一个包含整数的数组，每一个元素按对应的整数重复多次：

In [34]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

多维数组能在某个轴上进行重复：

In [35]:
arr = np.random.randn(2, 2)
arr

array([[-2.13777449, -1.37160911],
       [-0.43222896,  1.58212208]])

In [36]:
arr.repeat(2, axis=0)

array([[-2.13777449, -1.37160911],
       [-2.13777449, -1.37160911],
       [-0.43222896,  1.58212208],
       [-0.43222896,  1.58212208]])

如果没有指定轴，数组先会被压扁，这可能并不是我们希望的。同样的，我们也能传入一个数组，来指定分别重复多少次：

In [37]:
arr.repeat([2, 3], axis=0)

array([[-2.13777449, -1.37160911],
       [-2.13777449, -1.37160911],
       [-0.43222896,  1.58212208],
       [-0.43222896,  1.58212208],
       [-0.43222896,  1.58212208]])

In [38]:
arr.repeat([2, 3], axis=1)

array([[-2.13777449, -2.13777449, -1.37160911, -1.37160911, -1.37160911],
       [-0.43222896, -0.43222896,  1.58212208,  1.58212208,  1.58212208]])

tile，可以理解为把复制的部分沿着轴堆叠起来。视觉上的话，可以想象为堆叠在一起的磁砖：

In [39]:
arr

array([[-2.13777449, -1.37160911],
       [-0.43222896,  1.58212208]])

In [40]:
np.tile(arr, 2)

array([[-2.13777449, -1.37160911, -2.13777449, -1.37160911],
       [-0.43222896,  1.58212208, -0.43222896,  1.58212208]])

第二个参数是tile的数量，为标量，这种铺砖（tiliing）是以行为主（row by row），而不是列（column by column）。第二个参数可以是一个元组，用来制定铺砖的布局（the layout of the tiling）:

In [41]:
arr

array([[-2.13777449, -1.37160911],
       [-0.43222896,  1.58212208]])

In [42]:
np.tile(arr, (2, 1))

array([[-2.13777449, -1.37160911],
       [-0.43222896,  1.58212208],
       [-2.13777449, -1.37160911],
       [-0.43222896,  1.58212208]])

In [43]:
np.tile(arr, (3, 2))

array([[-2.13777449, -1.37160911, -2.13777449, -1.37160911],
       [-0.43222896,  1.58212208, -0.43222896,  1.58212208],
       [-2.13777449, -1.37160911, -2.13777449, -1.37160911],
       [-0.43222896,  1.58212208, -0.43222896,  1.58212208],
       [-2.13777449, -1.37160911, -2.13777449, -1.37160911],
       [-0.43222896,  1.58212208, -0.43222896,  1.58212208]])

# 5 Fancy Indexing Equivalents: take and put（花式索引）

第4章里有介绍到用整数进行花式索引来得到数组的子集：

In [44]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

有一个备选的ndarray方法，可以用于只在一个轴上进行选择的情况：

In [45]:
arr.take(inds)

array([700, 100, 200, 600])

In [47]:
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [48]:
arr.put(inds, [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

如果在其他轴上使用take，可以传入一个axis关键字：

In [49]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
arr

array([[ 1.35418322,  1.2602446 ,  0.33768923, -1.5975193 ],
       [-0.43616704,  0.92481945, -0.13766823,  0.60735354]])

In [50]:
arr.take(inds, axis=1)

array([[ 0.33768923,  1.35418322,  0.33768923,  1.2602446 ],
       [-0.13766823, -0.43616704, -0.13766823,  0.92481945]])

put不介绍axis参数，而是对数组的扁平版本（flattend, one-dimensional version）进行索引。因此，当我们需要用一个索引数组在某个粥上选择元素，使用花式索引是最方便的。